In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [7]:
print(np.array([1,2,3,4,5,6]))

[1 2 3 4 5 6]


In [13]:
# time comparison
import time
size = 1000000

# python list
l1 = range(size)
l2 = range(size)


# numpy array
n1 = np.array(size)
n2 = np.array(size)

# list time cal
start = time.time()
res =  [(x+y) for x, y  in zip(l1,l2)]
print("python list took: ", (time.time() - start)*1000, 'ms')


# nympy time cal
start = time.time()
res =  n1+n2
print("python list took: ", (time.time() - start)*1000, 'ms')


python list took:  566.986083984375 ms
python list took:  44.00920867919922 ms


In [15]:
566/44

12.863636363636363

In [17]:
207/14


14.785714285714286

In [19]:
# standard normal
mat1 = np.random.randn(3, 4)
print("standard normal matrix :\n", mat1)

standard normal matrix :
 [[-0.16354347  0.91543251  0.00376818  0.4934316 ]
 [-0.36797329 -1.38611896 -1.46539808 -0.7333365 ]
 [-0.19199922  0.63436968 -0.39018053 -0.01788789]]


In [21]:
# uniform distribution
mat1 = np.random.rand(4, 3)
print("uniform  distribution matrix :\n", mat1)

uniform  distribution matrix :
 [[0.47806113 0.74699398 0.52825908]
 [0.26493792 0.13894461 0.13548233]
 [0.14816198 0.76446562 0.98892061]
 [0.76261374 0.6899492  0.26266653]]


In [23]:
# array of random integers
mat1 = np.random.randint(low = 1, high= 100, size = (2,2))
print("Random integer matrix :\n", mat1)

Random integer matrix :
 [[22 78]
 [38 76]]


In [25]:
# getting the sequence of data
np.arange(start = 5, stop = 50, step = 5, dtype = float)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [29]:
np.arange(start = 5, stop = 50, step = 5)
type(np.arange(start = 5, stop = 50, step = 5))

numpy.ndarray

In [31]:
# attribute of array
a = np.array([[3,1],
              [5,6],
              [9,5]])
print("shape:", a.shape)
print("no of ele:", a.size)
print("data type:", a.dtype)
print("dimensions:", a.ndim)
print("Array:", a)
print("length or no of ele:", len(a))

shape: (3, 2)
no of ele: 6
data type: int32
dimensions: 2
Array: [[3 1]
 [5 6]
 [9 5]]
length or no of ele: 3


In [39]:

pip install pandas

In [47]:
import pandas as pd

df = pd.read_csv("C:/Users/bvm20/Desktop/Octane(20240614_192108).csv")
df.head()

Sample  Material1  Material2  Material3  Condition  Octane
0       1      55.33       1.72         54    1.66219   92.19
1       2      59.13       1.20         53    1.58399   92.74
2       3      57.39       1.42         55    1.61731   91.88
3       4      56.43       1.78         55    1.66228   92.80
4       5      55.98       1.58         54    1.63195   92.56

In [49]:
df.isnull().sum().any()

False

In [51]:
df.isnull().sum()

Sample       0
Material1    0
Material2    0
Material3    0
Condition    0
Octane       0
dtype: int64

In [53]:
df.duplicated().sum()

0

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Sample     82 non-null     int64  
 1   Material1  82 non-null     float64
 2   Material2  82 non-null     float64
 3   Material3  82 non-null     int64  
 4   Condition  82 non-null     float64
 5   Octane     82 non-null     float64
dtypes: float64(4), int64(2)
memory usage: 4.0 KB


In [57]:
df.dtypes

Sample         int64
Material1    float64
Material2    float64
Material3      int64
Condition    float64
Octane       float64
dtype: object

In [59]:
pip install matplotlib seaborn

Note: you may need to restart the kernel to use updated packages.
